# Generated by Django 4.1.3 on 2022-11-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('worker_hours', models.IntegerField(blank=True, null=True)),
                ('car', models.ManyToManyField(blank=True, to='car.car')),
            ],
        ),
    ]
