# Generated by Django 4.1.3 on 2022-11-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_remove_dealer_car_car_dealer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='dealer',
        ),
        migrations.AddField(
            model_name='dealer',
            name='car',
            field=models.ManyToManyField(blank=True, to='car.car'),
        ),
    ]
