# Generated by Django 4.1.4 on 2022-12-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('address', models.TextField(default='')),
                ('contact', models.IntegerField()),
                ('worker_hours', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('dealer', models.ManyToManyField(related_name='cars', to='cars.dealer')),
            ],
        ),
    ]
